name: Test & Deploy to Databricks

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest findspark

      - name: Run PySpark Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Run Job on Databricks (CD)
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: |
          databricks configure --token <<< "$DATABRICKS_HOST\n$DATABRICKS_TOKEN"
          databricks runs submit --json-file run_notebook.json
